### ISSUE TITLE
Error when setting up workspace

### ISSUE THREAD

**Issue by seth-stoothoff** [PG85/WorldPacker#1]
I downloaded worldpacker and tried to run the gradlew setupDecompWorkspace but it gave me the following error "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain". I noticed that the gradle-wrapper.jar was missing from the world packer gradle\wrapper folder. Can I use the  the gradle-wrapper.jar from the OTG git repository?

**Comment by PG85** [comment]
Hey @seth-stoothoff , thanks for mentioning this, I see the file is missing, I'll add it. A gradle-wrapper.jar of the correct version should do, so you should be able to use the one from the OTG repo, yeah. 

If you're not on Discord yet, join us at https://discord.gg/UXzdVTH for any questions about making presets and packaging them for end-users! Thanks and cheers.
